In [1]:
# Assignment 1

In [3]:
# Prakul Bajaj
# 102303863

In [4]:
# a)
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(np.flip(arr))

[5 4 6 3 2 1]


In [17]:
# b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
# Using Flatten
print(array1.flatten())
# Using Reshape
print(array1.reshape(-1))

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [19]:
# c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1,arr2)

True

In [25]:
# d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
# For x
val_x = np.bincount(x).argmax()
print(val_x)
indices_x = []
for i in range(len(x)):
    if(x[i]==val_x):
        indices_x.append(i)
print(indices_x)

# For y
val_y = np.bincount(y).argmax()
print(val_y)
indices_y = []
for i in range(len(y)):
    if(y[i]==val_y):
        indices_y.append(i)
print(indices_y)

1
[0, 5, 7, 8, 9]
1
[0, 1, 2]


In [32]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
# Sum of all elements
print(np.sum(gfg))
# Along the Row
print(np.sum(gfg,axis=1))
# Along the Column
print(np.sum(gfg,axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [36]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
# Sum of diagonal elements
print(np.trace(n_array))
# Eigen values
print(np.linalg.eigvals(n_array))
# Eigen Vector
print(np.linalg.eig(n_array))
# Inverse Vectors
print(np.linalg.inv(n_array))
# Determinant
print(np.linalg.det(n_array))

176
[28.097044   49.73460452 98.16835147]
EigResult(eigenvalues=array([28.097044  , 49.73460452, 98.16835147]), eigenvectors=array([[-0.34637121,  0.15017693,  0.4574917 ],
       [ 0.72784061,  0.4852124 ,  0.28447814],
       [-0.59184038, -0.8614034 ,  0.84248058]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [37]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(np.matmul(p,q))
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(np.matmul(p,q))

[[16 19]
 [26 31]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [39]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
# Inner product
print(np.inner(x,y))
# Outer product
print(np.outer(x,y))
# Cartesian product
print(np.cross(x,y))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


In [48]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
flattened = array.flatten()
print(np.percentile(array,[25,50,75]))
# Percentile for each row
print(np.percentile(array,[25,50,75], axis=1))
# Percentile for each column
print(np.percentile(array,[25,50,75],axis = 0))

[-3.5 -0.5  2.5]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [54]:
print(np.mean(flattened))
print(np.median(flattened))
print(np.std(flattened))

print(np.mean(array,axis=0))
print(np.mean(array,axis=1))
print(np.median(array,axis=0))
print(np.median(array,axis=1))
print(np.std(array,axis=0))
print(np.std(array,axis=1))

-0.5
-0.5
3.8622100754188224
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]
[-1.5  1.5 -1.5]
[ 1. -4.]
[2.5 3.5 4.5]
[2.05480467 4.78423336]


In [57]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [62]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [64]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array[array % 1 == 0])
print(array[array % 1 != 0])

[1. 2. 3. 2.]
[1.2 2.2]
